--Q1:The total revenue generated from all orders?
SELECT 
  SUM(Quantity * Price) AS TotalRevenue
FROM 
  SalesView;

--Q2:The average amount of money spent per order?
SELECT 
  CAST(SUM(Quantity * Price) / COUNT(DISTINCT OrderID)AS DECIMAL) AS AOV
FROM 
  SalesView;

--Q3:The total revenue generated for each category?
SELECT 
  CategoryName, SUM(Quantity * Price) AS SalesByCategory
FROM 
  SalesView
GROUP BY
  CategoryName
ORDER BY
  SalesByCategory DESC;

--Q4:The total revenue generated for each Product?
SELECT 
  ProductName, SUM(Quantity * Price) AS SalesByProduct
FROM 
  SalesView
GROUP BY
  ProductName
ORDER BY
  SalesByProduct DESC;

--Q5:The total revenue generated for each City?
SELECT 
  City, SUM(Quantity * Price) AS SalesByCity
FROM 
  SalesView
GROUP BY 
  City
ORDER BY
  SalesByCity DESC;

--Q6:The total revenue generated for each Country?
SELECT 
  Country, SUM(Quantity * Price) AS SalesByCountry
FROM     
  SalesView
GROUP BY 
  Country
ORDER BY
  SalesByCountry DESC;

--Q7:The top 5 cities with the highest sales revenue In USA?
SELECT 
  TOP 5 CITY, SUM(Quantity * Price) AS SalesByCity
FROM     
  SalesView
WHERE 
  Country='USA'
GROUP BY 
  City
ORDER BY
  SalesByCity DESC;

--Q8:The total revenue generated by each customer?
SELECT 
  CustomerName, SUM(Quantity * Price) AS SalesByCustomer
FROM 
  SalesView
GROUP BY 
  CustomerName
ORDER BY 
  SalesByCustomer DESC

--Q9:The total revenue associated with each shipping company?
SELECT 
  ShipperName, SUM(Quantity * Price) AS SalesByShipper
FROM 
  SalesView
GROUP BY 
  ShipperName
ORDER BY
  SalesByShipper DESC;

--Q10:Total sales associated with each supplier?
SELECT
  SupplierName, SUM(Quantity * Price) AS SalesBySupplier
FROM 
  SalesView
GROUP BY  
  SupplierName
ORDER BY SalesBySupplier DESC;

--Q11:The top 5 suppliers with the highest Sales Revenue?
SELECT 
  TOP 5 SupplierName, SUM(Quantity * Price) AS SalesBySupplier
FROM 
  SalesView
GROUP BY
  SupplierName
ORDER BY
   SalesBySupplier DESC;

--Q12:The total number of units sold for each product?
SELECT 
  ProductName, SUM(Quantity) AS TotalQuantitySold
FROM 
  SalesView
GROUP BY 
  ProductName
ORDER BY 
  TotalQuantitySold DESC;

--Q13:The Top 5 Best-Selling Products?
SELECT 
  TOP 5 ProductName, SUM(Quantity) AS TotalQuantitySold
FROM 
  SalesView
GROUP BY 
  ProductName
ORDER BY 
  TotalQuantitySold DESC;

--Q14:The average number of orders made by a customer?
SELECT 
  COUNT(DISTINCT OrderID) / COUNT(DISTINCT CustomerID) AS OrderFrequency
FROM
  SalesView;

--Q15:The number of orders made by each customer?
SELECT 
  CustomerName, COUNT(OrderID) AS OrdersPerCustomer
FROM
  SalesView
GROUP BY 
  CustomerName
ORDER BY 
  OrdersPerCustomer DESC;

--Q16:The number of orders received per month?
SELECT 
  DATENAME(MONTH, OrderDate) AS Month, COUNT(OrderID) AS OrdersPerMonth
FROM 
  SalesView
GROUP BY 
  DATENAME(MONTH, OrderDate)
ORDER BY
  OrdersPerMonth DESC



  








